Update testLocalyIAP.yml
22

diff --git a/.github/workflows/testLocalyIAP.yml b/.github/workflows/testLocalyIAP.yml
--- a/.github/workflows/testLocalyIAP.yml
+++ b/.github/workflows/testLocalyIAP.yml
@@ -18,8 +18,13 @@ jobs:
 
       - name: Ensure iOS 18.0 SDK
         run: |
-          sudo xcodebuild -downloadPlatform ios -allowProvisioningUpdates > sdk_install_log.txt 2>&1 || { cat sdk_install_log.txt; exit 1; }
-          xcodebuild -showsdks | grep iphoneos18.0 || { echo "iOS 18.0 SDK not found"; exit 1; }
+          for i in {1..3}; do
+            echo "Attempt $i to download iOS 18.0 SDK"
+            sudo xcodebuild -downloadPlatform ios -allowProvisioningUpdates > sdk_install_log.txt 2>&1 && break
+            cat sdk_install_log.txt
+            sleep 5
+          done
+          xcodebuild -showsdks | grep iphoneos18.0 || { echo "iOS 18.0 SDK not found"; xcrun simctl list; cat sdk_install_log.txt; exit 1; }
 
       - name: Setup Flutter
         uses: subosito/flutter-action@v2
